version: '3.5'

services:
  mysql:
    image: mysql:5
    container_name: gandalf
    networks: [fellowship]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3
    container_name: aragorn
    networks: [fellowship]

  microservice:
    build: ../..
    container_name: microservice
    networks: [fellowship]
    image: microservice
    command: ["sh", "/wait-and-run.sh", "/server-entrypoint.sh"]
    ports:
      - 8000:8000
    env_file:
      - ../.env

  command_consumer:
    build: ../..
    container_name: command_consumer
    networks: [fellowship]
    image: microservice
    command: ["sh", "/wait-and-run.sh", "/consumer-entrypoint.sh"]
    env_file:
      - ../.env

volumes:
  mysqldata:
    driver: local

networks:
  fellowship: