doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        connections:
            microservice:
                driver: pdo_mysql
                user: root
                password: root
                host: gandalf
                dbname: microservice
