# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    default_bus: query
    commandbus:
        query:
            middleware:
                - App\Middleware\DummyMiddleware
                - tactician.middleware.command_handler
