get_user:
    path: /users/{id}
    controller: Microservice\Infrastructure\Controller\Query\GetUserController
    methods: GET

delete_user:
    path: /users/{id}
    controller: Microservice\Infrastructure\Controller\Command\DeleteUserController
    methods: DELETE

save_user:
    path: /users/{id}
    controller: Microservice\Infrastructure\Controller\Command\SaveUserController
    methods: PUT
